<a href="https://colab.research.google.com/github/DharaniMohanachandran22/neural_networks/blob/main/neuralnetwoork(Tensorflow).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:



model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.10128209,  0.33131596,  1.0099081 , -0.5762309 , -0.19218406,
        -0.59753793, -0.41385418, -0.0015687 ,  0.06043316,  0.5161896 ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.07943293, 0.12242655, 0.24131504, 0.04940069, 0.07253078,
        0.04835924, 0.05811019, 0.08776182, 0.09337544, 0.14728725]],
      dtype=float32)

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

3.029098

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 11s 5ms/step - loss: 0.2943 - accuracy: 0.9141
Epoch 2/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.1436 - accuracy: 0.9563
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1071 - accuracy: 0.9674
Epoch 4/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0889 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0740 - accuracy: 0.9773


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0766 - accuracy: 0.9759 - 727ms/epoch - 2ms/step


[0.07660449296236038, 0.9758999943733215]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[3.90189108e-08, 1.46758964e-07, 1.52556140e-05, 4.69238788e-04,
        3.78682585e-10, 8.22672610e-06, 3.94284995e-12, 9.99492645e-01,
        1.53230008e-06, 1.29759255e-05],
       [5.55010899e-07, 6.03012195e-05, 9.99845147e-01, 4.34871363e-05,
        2.47584766e-16, 5.26103577e-07, 2.53060062e-08, 2.33402797e-10,
        4.99238122e-05, 3.84720901e-13],
       [7.68355108e-07, 9.97228682e-01, 2.68178235e-04, 8.34371094e-05,
        1.73185035e-04, 6.37213952e-06, 1.44526712e-05, 1.17403339e-03,
        1.04980799e-03, 9.19441050e-07],
       [9.99883294e-01, 1.23802923e-09, 1.20334753e-05, 1.61732635e-06,
        1.05315067e-07, 5.48262942e-05, 3.14874387e-06, 2.00607938e-05,
        1.64443202e-06, 2.33051742e-05],
       [1.04623301e-04, 8.30132629e-10, 6.10567031e-06, 1.13300516e-08,
        9.99027371e-01, 2.35561879e-06, 2.66615666e-06, 8.90298907e-05,
        9.56245799e-07, 7.67005607e-04]], dtype=float32)>